name: build
on: [deployment, push]

jobs:
  pakcer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.x'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install packer

      - name: Install Ansible
        run: |
          python3 -m pip install ansible

      - name: Retrieve Ansible playbooks
        run: |
          git clone https://github.com/ansible-playbooks-centos7/aws-s3.git
          git clone https://github.com/ansible-playbooks-centos7/redmine_restore.git

      - name: Set golden image ami id to environment variables
        run: |
          SOURCE_AMI_ID=$(aws ec2 describe-images \
          --owners $AMI_OWNER_ID \
          --filters "Name=name,Values=redmica_golden_image*" \
          --query 'Images[*][CreationDate, ImageId, Name]' \
          --output text | sort -r | awk 'NR==1 {print $2}')
          echo "SOURCE_AMI_ID=${SOURCE_AMI_ID}" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Execute pakcer build command
        run: |
          AMI_NAME="redmica_restore-`date \"+%s\"`"
          TAG_NAME="redmica_restore `date --date \"9 hours\" \"+%Y-%m-%d %H:%M:%S UTC+9\"`"

          packer build \
          -var "ami_name=${AMI_NAME}" \
          -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var "aws_region=${{ secrets.AWS_DEFAULT_REGION }}" \
          -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -var "s3_bucket=${{ secrets.AWS_S3_BUCKET_NAME }}" \
          -var "s3_object_name=${{ secrets.AWS_S3_OBJECT_NAME }}" \
          -var "source_ami_id=${SOURCE_AMI_ID}" \
          -var "local_file_name=${{ secrets.AWS_S3_OBJECT_NAME }}" \
          -var "working_dir=/tmp/s3" \
          -var "tag_name=${TAG_NAME}" \
          build.json

      - name: Show Go version
        run: |
          go version

      - name: Show Packer version
        run: |
          packer version

      - name: Show Ansible version
        run: |
          ansible --version
